/**
 * Dedicated Mock & Fallback Dataset
 * AgriBridge Farmer-Buyer Marketplace (SIH Project M5)
 * 
 * Provides realistic Indian agricultural data and local persistence
 * when real backend is offline or before backend endpoints are deployed.
 */

export const STORAGE_KEY_LISTINGS = 'agribridge_farmer_listings_v2'
export const STORAGE_KEY_REQUESTS = 'agribridge_connection_requests_v2'

export const MOCK_FARMER_PROFILE = {
  id: 'mock-farmer-01',
  name: 'Ramesh Patil',
  phone: '+91 98231 09842',
  location: {
    address: 'Dindori, Nashik, Maharashtra',
    latitude: 20.201,
    longitude: 73.832,
    district: 'Nashik',
    state: 'Maharashtra',
  },
  kycStatus: 'VERIFIED',
  trustScore: 97,
  farmSizeAcres: 12.5,
  rating: 4.9,
  reviewsCount: 38,
}

export const MOCK_INVENTORY_BATCHES = [
  {
    id: 'lst-101',
    farmerid: 'mock-farmer-01',
    farmerName: 'Ramesh Patil',
    crop: 'Onion (Nashik Red)',
    variety: 'Garwa / Late Kharif',
    category: 'Vegetables',
    quantity: 450,
    unit: 'Quintal',
    basePrice: 1280,
    expectedPrice: 1350,
    harvestDate: '2026-09-20',
    location: 'Dindori, Nashik, Maharashtra',
    coordinates: { latitude: 20.201, longitude: 73.832 },
    qualityGrade: 'Grade A Export',
    moisturePercent: 12.5,
    status: 'ACTIVE',
    verified: true,
  },
  {
    id: 'lst-102',
    farmerid: 'mock-farmer-01',
    farmerName: 'Ramesh Patil',
    crop: 'Wheat (Sharbati)',
    variety: 'Sharbati Gold',
    category: 'Grains',
    quantity: 800,
    unit: 'Quintal',
    basePrice: 2240,
    expectedPrice: 2320,
    harvestDate: '2026-09-15',
    location: 'Niphad, Nashik, Maharashtra',
    coordinates: { latitude: 20.082, longitude: 74.108 },
    qualityGrade: 'Grade A Premium',
    moisturePercent: 10.2,
    status: 'ACTIVE',
    verified: true,
  },
  {
    id: 'lst-103',
    farmerid: 'mock-farmer-01',
    farmerName: 'Ramesh Patil',
    crop: 'Tomato (Hybrid)',
    variety: 'Abhinav 1057',
    category: 'Vegetables',
    quantity: 180,
    unit: 'Quintal',
    basePrice: 880,
    expectedPrice: 940,
    harvestDate: '2026-09-22',
    location: 'Pimpalgaon, Nashik, Maharashtra',
    coordinates: { latitude: 20.171, longitude: 73.985 },
    qualityGrade: 'Grade A Table',
    moisturePercent: 14.0,
    status: 'IN_NEGOTIATION',
    verified: true,
  },
]

export const MOCK_VERIFIED_BUYERS = [
  {
    id: 'byr-201',
    name: 'Kisan Agro Processing Ltd.',
    contactPerson: 'Vikram Joshi (Procurement Head)',
    phone: '+91 98230 44120',
    email: 'procurement@kisanagro.in',
    type: 'Food Processor / Exporter',
    kycVerified: true,
    verificationTier: 'KYC & GST VERIFIED',
    trustScore: 98,
    transactionsCompleted: 142,
    location: 'Nashik MIDC, Maharashtra',
    latitude: 19.973,
    longitude: 73.742,
    distance: 18,
    crops: ['Onion (Nashik Red)', 'Tomato (Hybrid)', 'Potato'],
    capacity: '2,500 Qtl/month',
    offeredPrices: {
      'Onion (Nashik Red)': 1340,
      'Tomato (Hybrid)': 920,
      'Potato': 760,
    },
    paymentTerms: '50% Advance on loading, 50% upon delivery (24h)',
    freightStatus: true, // Free pickup
    freightRatePerKmQtl: 1.15,
  },
  {
    id: 'byr-202',
    name: 'Sahyadri Farmers Producer Co.',
    contactPerson: 'Dr. Ananya Deshmukh',
    phone: '+91 94222 18905',
    email: 'directbuy@sahyadrifarms.com',
    type: 'Farmer Producer Company (FPC)',
    kycVerified: true,
    verificationTier: 'GOVT. ACCREDITED FPC',
    trustScore: 96,
    transactionsCompleted: 310,
    location: 'Mohadi, Dindori, Nashik',
    latitude: 20.150,
    longitude: 73.865,
    distance: 8,
    crops: ['Tomato (Hybrid)', 'Grapes', 'Onion (Nashik Red)', 'Soybean'],
    capacity: '5,000 Qtl/month',
    offeredPrices: {
      'Tomato (Hybrid)': 945,
      'Onion (Nashik Red)': 1320,
      'Soybean': 4310,
    },
    paymentTerms: 'Direct bank transfer within 48 hours of weighment',
    freightStatus: false,
    freightRatePerKmQtl: 1.25,
  },
  {
    id: 'byr-203',
    name: 'Metro Wholesale Cash & Carry',
    contactPerson: 'Sanjay Malhotra',
    phone: '+91 98110 59281',
    email: 'agri.procure@metro-wholesale.in',
    type: 'Modern Retail Chain',
    kycVerified: true,
    verificationTier: 'CORPORATE VERIFIED',
    trustScore: 94,
    transactionsCompleted: 88,
    location: 'Thane Logistics Hub, Mumbai',
    latitude: 19.218,
    longitude: 72.978,
    distance: 84,
    crops: ['Wheat (Sharbati)', 'Rice (Basmati)', 'Onion (Nashik Red)'],
    capacity: '10,000 Qtl/month',
    offeredPrices: {
      'Wheat (Sharbati)': 2350,
      'Onion (Nashik Red)': 1390,
      'Rice (Basmati)': 3650,
    },
    paymentTerms: '100% digital payment in 3 banking days',
    freightStatus: true,
    freightRatePerKmQtl: 0.95,
  },
  {
    id: 'byr-204',
    name: 'Patanjali Agro Commodities',
    contactPerson: 'Rajnish Kumar',
    phone: '+91 97180 33819',
    email: 'rawmaterials@patanjaliagro.org',
    type: 'Large Manufacturer',
    kycVerified: true,
    verificationTier: 'KYC VERIFIED',
    trustScore: 91,
    transactionsCompleted: 165,
    location: 'Jalgaon Processing Zone, Maharashtra',
    latitude: 21.007,
    longitude: 75.562,
    distance: 142,
    crops: ['Wheat (Sharbati)', 'Soybean', 'Maize', 'Mustard'],
    capacity: '15,000 Qtl/month',
    offeredPrices: {
      'Wheat (Sharbati)': 2310,
      'Soybean': 4280,
      'Maize': 1720,
    },
    paymentTerms: 'Prompt payment upon quality certification',
    freightStatus: false,
    freightRatePerKmQtl: 1.10,
  },
  {
    id: 'byr-205',
    name: 'Jai Kisan Mandi Traders',
    contactPerson: 'Gopal Mundra',
    phone: '+91 93700 81290',
    email: 'gopal.mundra@jaikisan.co',
    type: 'Commission Agent / Aggregator',
    kycVerified: false,
    verificationTier: 'SELF-REPORTED',
    trustScore: 78,
    transactionsCompleted: 24,
    location: 'Lasalgaon Mandi Yard, Nashik',
    latitude: 20.147,
    longitude: 74.225,
    distance: 34,
    crops: ['Onion (Nashik Red)', 'Maize'],
    capacity: '1,200 Qtl/month',
    offeredPrices: {
      'Onion (Nashik Red)': 1290,
      'Maize': 1660,
    },
    paymentTerms: 'Cash or Cheque on delivery',
    freightStatus: false,
    freightRatePerKmQtl: 1.30,
  },
]

export const MOCK_REGIONAL_MANDIS = [
  {
    id: 'mnd-01',
    name: 'Lasalgaon APMC (Asia’s Largest Onion Market)',
    distanceKm: 34,
    prices: {
      'Onion (Nashik Red)': 1280,
      'Wheat (Sharbati)': 2190,
      'Tomato (Hybrid)': 860,
    },
    mandiCessPercent: 1.5,
    unloadingCostPerQtl: 25,
    coordinates: { latitude: 20.147, longitude: 74.225 },
  },
  {
    id: 'mnd-02',
    name: 'Pimpalgaon Baswant APMC',
    distanceKm: 18,
    prices: {
      'Onion (Nashik Red)': 1270,
      'Tomato (Hybrid)': 890,
      'Soybean': 4180,
    },
    mandiCessPercent: 1.25,
    unloadingCostPerQtl: 20,
    coordinates: { latitude: 20.171, longitude: 73.985 },
  },
  {
    id: 'mnd-03',
    name: 'Pune APMC (Gultekdi Yard)',
    distanceKm: 165,
    prices: {
      'Onion (Nashik Red)': 1360,
      'Wheat (Sharbati)': 2280,
      'Tomato (Hybrid)': 930,
    },
    mandiCessPercent: 1.8,
    unloadingCostPerQtl: 30,
    coordinates: { latitude: 18.498, longitude: 73.865 },
  },
  {
    id: 'mnd-04',
    name: 'Vashi APMC (Navi Mumbai Wholesale Market)',
    distanceKm: 155,
    prices: {
      'Onion (Nashik Red)': 1410,
      'Wheat (Sharbati)': 2340,
      'Tomato (Hybrid)': 970,
    },
    mandiCessPercent: 2.0,
    unloadingCostPerQtl: 35,
    coordinates: { latitude: 19.076, longitude: 73.003 },
  },
]

export const MOCK_INITIAL_CONNECTIONS = [
  {
    id: 'req-301',
    farmerid: 'mock-farmer-01',
    buyerId: 'byr-201',
    buyerName: 'Kisan Agro Processing Ltd.',
    crop: 'Onion (Nashik Red)',
    quantity: 300,
    unit: 'Quintal',
    quotedPrice: 1340,
    farmerAskPrice: 1350,
    logisticsMethod: 'BUYER_ARRANGED_TRANSPORT',
    targetDate: '2026-09-28',
    status: 'PENDING',
    message: 'Requires Grade A onions sorted in 50kg ventilated mesh bags. Pickup at farmgate.',
    auditTrail: [
      {
        timestamp: '2026-09-24T10:15:00.000Z',
        actor: 'BUYER',
        action: 'Connection Request Initiated',
        oldStatus: null,
        newStatus: 'PENDING',
        price: 1340,
        quantity: 300,
        message: 'Initial buyer inquiry submitted.',
      },
    ],
    verifiedDeal: true,
  },
  {
    id: 'req-302',
    farmerid: 'mock-farmer-01',
    buyerId: 'byr-202',
    buyerName: 'Sahyadri Farmers Producer Co.',
    crop: 'Tomato (Hybrid)',
    quantity: 150,
    unit: 'Quintal',
    quotedPrice: 940,
    farmerAskPrice: 940,
    logisticsMethod: 'FARMER_DELIVERY',
    targetDate: '2026-09-26',
    status: 'ACCEPTED',
    message: 'Agreed on ₹940/qtl for ripe table tomatoes. Delivery at Mohadi Packhouse by Saturday 8 AM.',
    auditTrail: [
      {
        timestamp: '2026-09-23T14:40:00.000Z',
        actor: 'BUYER',
        action: 'Connection Request Initiated',
        oldStatus: null,
        newStatus: 'PENDING',
        price: 940,
        quantity: 150,
        message: 'Batch inquiry received.',
      },
      {
        timestamp: '2026-09-24T09:00:00.000Z',
        actor: 'FARMER',
        action: 'Deal Accepted & Confirmed',
        oldStatus: 'PENDING',
        newStatus: 'ACCEPTED',
        price: 940,
        quantity: 150,
        message: 'Farmer locked price.',
      },
    ],
    verifiedDeal: true,
  },
  {
    id: 'req-303',
    farmerid: 'mock-farmer-01',
    buyerId: 'byr-203',
    buyerName: 'Metro Wholesale Cash & Carry',
    crop: 'Wheat (Sharbati)',
    quantity: 500,
    unit: 'Quintal',
    quotedPrice: 2320,
    farmerAskPrice: 2340,
    logisticsMethod: 'BUYER_ARRANGED_TRANSPORT',
    targetDate: '2026-10-02',
    status: 'NEGOTIATING',
    message: 'Buyer offered ₹2320/qtl; Farmer countered at ₹2340/qtl due to low moisture certification.',
    auditTrail: [
      {
        timestamp: '2026-09-22T11:20:00.000Z',
        actor: 'BUYER',
        action: 'Initial Offer Proposed',
        oldStatus: null,
        newStatus: 'PENDING',
        price: 2300,
        quantity: 500,
        message: 'Offer at ₹2,300/qtl.',
      },
      {
        timestamp: '2026-09-23T16:15:00.000Z',
        actor: 'FARMER',
        action: 'Counter Offer Proposed',
        oldStatus: 'PENDING',
        newStatus: 'NEGOTIATING',
        price: 2340,
        quantity: 500,
        message: 'Farmer countered at ₹2,340/qtl.',
      },
      {
        timestamp: '2026-09-24T11:00:00.000Z',
        actor: 'BUYER',
        action: 'Revised Offer Received',
        oldStatus: 'NEGOTIATING',
        newStatus: 'NEGOTIATING',
        price: 2320,
        quantity: 500,
        message: 'Buyer revised to ₹2,320/qtl.',
      },
    ],
    verifiedDeal: true,
  },
]

export function getStoredData(key, fallback) {
  try {
    const raw = localStorage.getItem(key)
    return raw ? JSON.parse(raw) : fallback
  } catch {
    return fallback
  }
}

export function setStoredData(key, data) {
  try {
    localStorage.setItem(key, JSON.stringify(data))
  } catch (err) {
    console.error('Storage write error:', err)
  }
}
